### PR TITLE
Remove URL link

### PR DESCRIPTION
**Pull request by beenanikhil**

### CODE REVIEW

**Comment by CharlesTBetz** [comment]
I'm curious why this is preferable?

**Comment by beenanikhil** [comment]
In original Lab for feature branch work Flow URL link is not working.It should be https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow ---instead of 
https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflowtree

**Comment by CharlesTBetz** [comment]
Can you change the pull request to keep 2 links?

**Comment by beenanikhil** [comment]
It was late you already changed it..

**Pull request closed without merging**
